name: spajam_stech
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  go_router: ^4.2.8
  isar: ^2.5.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.0.8
  json_serializable: ^6.3.1
  pedantic_mono: ^1.19.2
  simple_logger: ^1.9.0

flutter:
  uses-material-design: true
  fonts:
    - family: AoyagiKouzanFontT
      fonts:
        - asset: assets/fonts/AoyagiKouzanTOTF.otf
