// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1zhzvgw7txso4mFzMY4Qn0bRg7d_DXtA',
    appId: '1:890289712662:web:0d158a967f21ba33b6cf37',
    messagingSenderId: '890289712662',
    projectId: 'senkohanabi-6b670',
    authDomain: 'senkohanabi-6b670.firebaseapp.com',
    storageBucket: 'senkohanabi-6b670.appspot.com',
    measurementId: 'G-9RF28XZYH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMdyQoJjG2UkYf6hpXCVv1XMQopbQxQkg',
    appId: '1:890289712662:android:649986518c3b400eb6cf37',
    messagingSenderId: '890289712662',
    projectId: 'senkohanabi-6b670',
    storageBucket: 'senkohanabi-6b670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwtTPE2Izro6iTDcq8JoQUQH-6YaK69Y',
    appId: '1:890289712662:ios:e1ac579b816f168bb6cf37',
    messagingSenderId: '890289712662',
    projectId: 'senkohanabi-6b670',
    storageBucket: 'senkohanabi-6b670.appspot.com',
    iosClientId:
        '890289712662-0gmbpul50cjf7fjuqp9d8hjhgv0f5dt7.apps.googleusercontent.com',
    iosBundleId: 'com.norihanda.spajamStech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwtTPE2Izro6iTDcq8JoQUQH-6YaK69Y',
    appId: '1:890289712662:ios:e1ac579b816f168bb6cf37',
    messagingSenderId: '890289712662',
    projectId: 'senkohanabi-6b670',
    storageBucket: 'senkohanabi-6b670.appspot.com',
    iosClientId:
        '890289712662-0gmbpul50cjf7fjuqp9d8hjhgv0f5dt7.apps.googleusercontent.com',
    iosBundleId: 'com.norihanda.spajamStech',
  );
}
